#!/usr/bin/env python
import sys
import fileinput
import re


def format(commit):
    tmpl = (
            "\033[1;31m{0}\033[0m"
            "- {1} "
            "\033[0;32m({2} {3}) "
            "\033[0;34m<{4}>\033[0m")
    return tmpl.format(
            commit['rev'], commit['msg'], commit['date'],
            commit['time'], commit['author'])


def main():
    commit = {}
    for line in fileinput.input():
        if re.search('^r[0-9]+ \| ', line):
            detail = line.split(' | ')
            commit = {
                'rev': detail[0],
                'author': detail[1],
                'date': detail[2].split(' ')[0],
                'time': detail[2].split(' ')[1]}
        elif not re.search('^-*$', line) and 'msg' not in commit:
            commit['msg'] = line[0:line.find('\n')]
        elif re.search('^-+$', line) and 'rev' in commit:
            print(format(commit))
            commit.clear()


if __name__ == '__main__':
    if not sys.stdin.isatty():
        main()
